name: kubectl-bai-config auto-release

on:
  push:
    paths-ignore:
      - "plugins/bai-config.yaml"
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Get PR from merged commit to the default branch
      - name: Get merged pull request
        id: get-merged-pull-request
        env:
          GH_TOKEN: ${{ secrets.PAT_ORG_ADMIN_REPO_ALL }}
        run: |
          labels=$(gh api "repos/${{ github.repository }}/commits/${{ github.sha }}/pulls" \
            --jq '[.[].labels[].name] | join(",")')
          echo "labels=${labels}" >> "$GITHUB_OUTPUT"

      # Publish Release
      - uses: release-drafter/release-drafter@v6
        id: release-drafter
        with:
          publish: ${{ !contains(steps.get-merged-pull-request.outputs.labels, 'no-release') }}
          prerelease: false
          config-name: auto-release.yml
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_ORG_ADMIN_REPO_ALL }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_ORG_ADMIN_REPO_ALL }}
