name: kubectl-bai-config ci
permissions:
  contents: read

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.18

      - name: GoReleaser snapshot build
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --snapshot
