name: kubectl-bai-config ci

on:
  pull_request:

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kubectl-bai-config
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
      - name: Test
        run: go test ./...
      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v7
        with:
          version: "~> v2"
          args: release --snapshot --clean
